### ISSUE TITLE
打印底部有水印

### ISSUE THREAD

**Issue by linnjie** [a854363956/grid-utils#2]
WEB端有水印没错，但是C/S客户端应该没水印才对？

![图片](https://user-images.githubusercontent.com/33271850/71344248-fee88a80-259c-11ea-8cb5-a6c63724bc89.png)

**Comment by a854363956** [comment]
是打印的出来的文件有水印，还说预览的时候有水印？ 水印只有在预览的时候才出现，打印的时候是没有水印的。

**Comment by a854363956** [comment]
我测试一下，其他cs中是否存在此现象，如果存在在下个版本中修复水印问题

**Comment by linnjie** [comment]
@a854363956 
感谢回复，你提示了我。是这样的，如果用 url 载入模板和数据，预览和打印都会出现水印，如果用字符串、json 等载入就不会。
